### ISSUE TITLE
TypeError: 'str' does not support the buffer interface under Python 3

### ISSUE THREAD

**Issue by tiktuk** [linsomniac/python-memcached#54]
I get this error under Python 3.4 using linsomniac/python-memcached@2251916a6a1e8f35609d8d963f68ccab8c1b9402:

```
Error handling request
Traceback (most recent call last):
  File "/user/.virtualenvs/project/lib/python3.4/site-packages/django/core/handlers/base.py", line 199, in get_response
    response = middleware_method(request, response)
  File "/user/.virtualenvs/project/lib/python3.4/site-packages/mezzanine/core/middleware.py", line 192, in process_response
    context = RequestContext(request)
  File "/user/.virtualenvs/project/lib/python3.4/site-packages/django/template/context.py", line 169, in __init__
    self.update(processor(request))
  File "/user/.virtualenvs/project/lib/python3.4/site-packages/mezzanine/conf/context_processors.py", line 40, in settings
    settings_dict = cache_get(cache_key)
  File "/user/.virtualenvs/project/lib/python3.4/site-packages/mezzanine/utils/cache.py", line 48, in cache_get
    packed = cache.get(_hashed_key(key))
  File "/user/.virtualenvs/project/lib/python3.4/site-packages/django/core/cache/backends/memcached.py", line 75, in get
    val = self._cache.get(key)
  File "/user/.virtualenvs/project/lib/python3.4/site-packages/memcache.py", line 1002, in get
    return self._get('get', key)
  File "/user/.virtualenvs/project/lib/python3.4/site-packages/memcache.py", line 986, in _get
    return _unsafe_get()
  File "/user/.virtualenvs/project/lib/python3.4/site-packages/memcache.py", line 957, in _unsafe_get
    server.send_cmd("%s %s" % (cmd, key))
  File "/user/.virtualenvs/project/lib/python3.4/site-packages/memcache.py", line 1299, in send_cmd
    self.socket.sendall(cmd + '\r\n')
TypeError: 'str' does not support the buffer interface

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/user/.virtualenvs/project/lib/python3.4/site-packages/gunicorn/workers/sync.py", line 93, in handle
    self.handle_request(listener, req, client, addr)
  File "/user/.virtualenvs/project/lib/python3.4/site-packages/gunicorn/workers/sync.py", line 134, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/user/.virtualenvs/project/lib/python3.4/site-packages/django/core/handlers/wsgi.py", line 206, in __call__
    response = self.get_response(request)
  File "/user/.virtualenvs/project/lib/python3.4/site-packages/django/core/handlers/base.py", line 203, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/user/.virtualenvs/project/lib/python3.4/site-packages/django/core/handlers/base.py", line 236, in handle_uncaught_exception
    return callback(request, **param_dict)
  File "/user/.virtualenvs/project/lib/python3.4/site-packages/django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/user/.virtualenvs/project/lib/python3.4/site-packages/mezzanine/core/views.py", line 220, in server_error
    context = RequestContext(request, {"STATIC_URL": settings.STATIC_URL})
  File "/user/.virtualenvs/project/lib/python3.4/site-packages/django/template/context.py", line 169, in __init__
    self.update(processor(request))
  File "/user/.virtualenvs/project/lib/python3.4/site-packages/mezzanine/conf/context_processors.py", line 40, in settings
    settings_dict = cache_get(cache_key)
  File "/user/.virtualenvs/project/lib/python3.4/site-packages/mezzanine/utils/cache.py", line 48, in cache_get
    packed = cache.get(_hashed_key(key))
  File "/user/.virtualenvs/project/lib/python3.4/site-packages/django/core/cache/backends/memcached.py", line 75, in get
    val = self._cache.get(key)
  File "/user/.virtualenvs/project/lib/python3.4/site-packages/memcache.py", line 1002, in get
    return self._get('get', key)
  File "/user/.virtualenvs/project/lib/python3.4/site-packages/memcache.py", line 986, in _get
    return _unsafe_get()
  File "/user/.virtualenvs/project/lib/python3.4/site-packages/memcache.py", line 957, in _unsafe_get
    server.send_cmd("%s %s" % (cmd, key))
  File "/user/.virtualenvs/project/lib/python3.4/site-packages/memcache.py", line 1299, in send_cmd
    self.socket.sendall(cmd + '\r\n')
TypeError: 'str' does not support the buffer interface
```

**Comment by linsomniac** [comment]
#67 has been released, is this fixed?
