### ISSUE TITLE
ImportError on six when running tests

### ISSUE THREAD

**Issue by nicholasserra** [linsomniac/python-memcached#77]
Following the docs on running tests and hitting an ImportError while running. Six is definitely installed, not sure if this is a venv issue, or something that's been brought up before?

```
(memcached)nick@localhost python-memcached (master) $ tox -e py27
py27 create: /Users/nick/Code/python-memcached/.tox/py27
py27 installdeps: -r/Users/nick/Code/python-memcached/requirements.txt, -r/Users/nick/Code/python-memcached/test-requirements.txt
py27 develop-inst: /Users/nick/Code/python-memcached
py27 installed: argparse==1.3.0,coverage==3.7.1,flake8==2.2.4,hacking==0.10.2,mccabe==0.2.1,nose==1.3.7,pbr==0.10.8,pep8==1.5.7,pyflakes==0.8.1,-e git+https://github.com/nicholasserra/python-memcached.git@664bd3e23fe500fbde4c70636e2d24c8fd2f35af#egg=python_memcached-master,six==1.9.0,stevedore==1.2.0,virtualenv==12.0.2,virtualenv-clone==0.2.5,virtualenvwrapper==4.3.1,wsgiref==0.1.2
py27 runtests: PYTHONHASHSEED='3267181802'
py27 runtests: commands[0] | nosetests
EE
======================================================================
ERROR: Failure: ImportError (No module named six)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/nick/Code/python-memcached/.tox/py27/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/nick/Code/python-memcached/.tox/py27/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/nick/Code/python-memcached/.tox/py27/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/nick/Code/python-memcached/tests/test_memcache.py", line 5, in <module>
    import six
ImportError: No module named six

======================================================================
ERROR: Failure: ImportError (No module named six)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/nick/Code/python-memcached/.tox/py27/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/nick/Code/python-memcached/.tox/py27/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/nick/Code/python-memcached/.tox/py27/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/nick/Code/python-memcached/tests/test_setmulti.py", line 17, in <module>
    import memcache
  File "/Users/nick/Code/python-memcached/memcache.py", line 60, in <module>
    import six
ImportError: No module named six

----------------------------------------------------------------------
Ran 2 tests in 0.004s

FAILED (errors=2)
ERROR: InvocationError: '/Users/nick/Code/python-memcached/.tox/py27/bin/nosetests'
```

**Comment by linsomniac** [comment]
Doesn't seem like "import six" failing could be a python-memcached issue.

**Comment by nicholasserra** [comment]
It's not an issue with the memcache script, but is an issue with running the tests. As described in the README, the commands to run tests didn't seem to work. I instead had to replicate how travis was running them and install nose and run nosetests.

**Comment by linsomniac** [comment]
I can't reproduce it.
